# Main categories for articles
MAIN_CATEGORIES = (
    ("Select a category", "Select a category"),
    ("IT", "Information Technology"),
    ("Engineering", "Engineering"),
    ("Medicine", "Medicine"),
    ("Business", "Business"),
    ("Science", "Science"),
    ("Art", "Art"),
    ("Sports", "Sports"),
    ("Food", "Food"),
    ("Travel", "Travel"),
    ("Music", "Music"),
    ("History", "History"),
    ("Fashion", "Fashion"),
    ("Politics", "Politics"),
    ("Education", "Education"),
    ("Environment", "Environment"),
    ("Health", "Health"),
    ("Fitness", "Fitness"),
    ("Parenting", "Parenting"),
    ("Technology", "Technology"),
    ("Gaming", "Gaming"),
    ("Pets", "Pets"),
    ("Automotive", "Automotive"),
    ("Movies", "Movies"),
    ("Books", "Books"),
    ("Home", "Home"),
    ("Gardening", "Gardening"),
    ("Finance", "Finance"),
    ("Photography", "Photography"),
    ("DIY", "DIY"),
    ("Spirituality", "Spirituality"),
)

# Subcategories for each main category
SUBCATEGORIES = {
    "IT": (
        ("Programming", "Programming"),
        ("Networking", "Networking"),
        ("Cybersecurity", "Cybersecurity"),
        ("Web Development", "Web Development"),
        ("Mobile Development", "Mobile Development"),
        ("Data Science", "Data Science"),
        ("Machine Learning", "Machine Learning"),
        ("Artificial Intelligence", "Artificial Intelligence"),
        ("Blockchain", "Blockchain"),
        ("Game Development", "Game Development"),
        ("Cloud Computing", "Cloud Computing"),
        ("Software Engineering", "Software Engineering"),
        ("Hardware", "Hardware"),
    ),
    "Engineering": (
        ("Mechanical", "Mechanical Engineering"),
        ("Electrical", "Electrical Engineering"),
        ("Civil", "Civil Engineering"),
        ("Aerospace", "Aerospace Engineering"),
        ("Chemical", "Chemical Engineering"),
        ("Computer", "Computer Engineering"),
        ("Biomedical", "Biomedical Engineering"),
        ("Environmental", "Environmental Engineering"),
        ("Materials", "Materials Engineering"),
        ("Nuclear", "Nuclear Engineering"),
        ("Industrial", "Industrial Engineering"),
        ("Robotics", "Robotics Engineering"),
    ),
    "Medicine": (
        ("Cardiology", "Cardiology"),
        ("Neurology", "Neurology"),
        ("Oncology", "Oncology"),
        ("Dentistry", "Dentistry"),
        ("Pediatrics", "Pediatrics"),
        ("Gynecology", "Gynecology"),
        ("Orthopedics", "Orthopedics"),
        ("Psychiatry", "Psychiatry"),
        ("Dermatology", "Dermatology"),
        ("Ophthalmology", "Ophthalmology"),
        ("Radiology", "Radiology"),
        ("Surgery", "Surgery"),
        ("Pathology", "Pathology"),
    ),
    "Business": (
        ("Entrepreneurship", "Entrepreneurship"),
        ("Marketing", "Marketing"),
        ("Finance", "Finance"),
        ("Management", "Management"),
        ("Economics", "Economics"),
        ("Accounting", "Accounting"),
        ("Human Resources", "Human Resources"),
        ("International Business", "International Business"),
        ("Sales", "Sales"),
        ("Supply Chain Management", "Supply Chain Management"),
        ("Business Strategy", "Business Strategy"),
        ("Leadership", "Leadership"),
    ),
    "Science": (
        ("Physics", "Physics"),
        ("Chemistry", "Chemistry"),
        ("Biology", "Biology"),
        ("Astronomy", "Astronomy"),
        ("Geology", "Geology"),
        ("Ecology", "Ecology"),
        ("Psychology", "Psychology"),
        ("Sociology", "Sociology"),
        ("Anthropology", "Anthropology"),
        ("Paleontology", "Paleontology"),
        ("Botany", "Botany"),
        ("Zoology", "Zoology"),
        ("Oceanography", "Oceanography"),
    ),
    "Art": (
        ("Painting", "Painting"),
        ("Sculpture", "Sculpture"),
        ("Photography", "Photography"),
        ("Drawing", "Drawing"),
        ("Digital Art", "Digital Art"),
        ("Music", "Music"),
        ("Dance", "Dance"),
        ("Theater", "Theater"),
        ("Film", "Film"),
        ("Literature", "Literature"),
        ("Poetry", "Poetry"),
        ("Crafts", "Crafts"),
        ("Ceramics", "Ceramics"),
    ),
    "Sports": (
        ("Football", "Football"),
        ("Basketball", "Basketball"),
        ("Baseball", "Baseball"),
        ("Soccer", "Soccer"),
        ("Tennis", "Tennis"),
        ("Golf", "Golf"),
        ("Swimming", "Swimming"),
        ("Athletics", "Athletics"),
        ("Volleyball", "Volleyball"),
        ("Cricket", "Cricket"),
        ("Hockey", "Hockey"),
        ("Martial Arts", "Martial Arts"),
        ("Wrestling", "Wrestling"),
    ),
    "Food": (
        ("Recipes", "Recipes"),
        ("Cooking Techniques", "Cooking Techniques"),
        ("Baking", "Baking"),
        ("International Cuisine", "International Cuisine"),
        ("Healthy Eating", "Healthy Eating"),
        ("Restaurant Reviews", "Restaurant Reviews"),
        ("Food History", "Food History"),
        ("Food Culture", "Food Culture"),
        ("Vegetarian/Vegan", "Vegetarian/Vegan"),
        ("Food Photography", "Food Photography"),
        ("Food Science", "Food Science"),
    ),
    "Travel": (
        ("Destinations", "Destinations"),
        ("Travel Tips", "Travel Tips"),
        ("Cultural Experiences", "Cultural Experiences"),
        ("Adventure Travel", "Adventure Travel"),
        ("Food Travel", "Food Travel"),
        ("Budget Travel", "Budget Travel"),
        ("Solo Travel", "Solo Travel"),
        ("Family Travel", "Family Travel"),
        ("Road Trips", "Road Trips"),
        ("Luxury Travel", "Luxury Travel"),
        ("Travel Photography", "Travel Photography"),
        ("Travel Guides", "Travel Guides"),
    ),
    "Music": (
        ("Genres", "Genres"),
        ("Artists", "Artists"),
        ("Album Reviews", "Album Reviews"),
        ("Music History", "Music History"),
        ("Concerts", "Concerts"),
        ("Music Production", "Music Production"),
        ("Songwriting", "Songwriting"),
        ("Music Theory", "Music Theory"),
        ("Music Instruments", "Music Instruments"),
        ("Music Festivals", "Music Festivals"),
        ("Music Industry", "Music Industry"),
        ("Music Technology", "Music Technology"),
    ),
    "History": (
        ("Ancient History", "Ancient History"),
        ("Medieval History", "Medieval History"),
        ("Renaissance", "Renaissance"),
        ("World War I", "World War I"),
        ("World War II", "World War II"),
        ("Cold War", "Cold War"),
        ("Ancient Civilizations", "Ancient Civilizations"),
        ("Modern History", "Modern History"),
        ("Historical Figures", "Historical Figures"),
        ("Archaeology", "Archaeology"),
        ("Historical Events", "Historical Events"),
    ),
    "Fashion": (
        ("Fashion Trends", "Fashion Trends"),
        ("Fashion Designers", "Fashion Designers"),
        ("Fashion Tips", "Fashion Tips"),
        ("Sustainable Fashion", "Sustainable Fashion"),
        ("Fashion History", "Fashion History"),
        ("Celebrity Fashion", "Celebrity Fashion"),
        ("Street Style", "Street Style"),
        ("Fashion Accessories", "Fashion Accessories"),
        ("Haute Couture", "Haute Couture"),
        ("Beauty & Makeup", "Beauty & Makeup"),
        ("Fashion Photography", "Fashion Photography"),
        ("Fashion Industry", "Fashion Industry"),
    ),
    "Politics": (
        ("Political News", "Political News"),
        ("Elections", "Elections"),
        ("Government Policies", "Government Policies"),
        ("International Relations", "International Relations"),
        ("Political Ideologies", "Political Ideologies"),
        ("Social Issues", "Social Issues"),
        ("Political Commentary", "Political Commentary"),
        ("Political History", "Political History"),
        ("Political Leaders", "Political Leaders"),
        ("Human Rights", "Human Rights"),
        ("Political Activism", "Political Activism"),
    ),
    "Education": (
        ("Teaching", "Teaching"),
        ("Educational Technology", "Educational Technology"),
        ("Curriculum Development", "Curriculum Development"),
        ("Online Learning", "Online Learning"),
        ("Special Education", "Special Education"),
        ("Higher Education", "Higher Education"),
        ("Early Childhood Education", "Early Childhood Education"),
        ("Education Policy", "Education Policy"),
        ("Education Psychology", "Education Psychology"),
        ("Education Trends", "Education Trends"),
        ("Educational Resources", "Educational Resources"),
        ("Language Learning", "Language Learning"),
    ),
    "Environment": (
        ("Climate Change", "Climate Change"),
        ("Conservation", "Conservation"),
        ("Renewable Energy", "Renewable Energy"),
        ("Sustainability", "Sustainability"),
        ("Pollution", "Pollution"),
        ("Wildlife", "Wildlife"),
        ("Environmental Activism", "Environmental Activism"),
        ("Green Living", "Green Living"),
        ("Natural Disasters", "Natural Disasters"),
        ("Environmental Policy", "Environmental Policy"),
        ("Eco-friendly Products", "Eco-friendly Products"),
        ("Environmental Education", "Environmental Education"),
    ),
    "Health": (
        ("Nutrition", "Nutrition"),
        ("Fitness", "Fitness"),
        ("Mental Health", "Mental Health"),
        ("Wellness", "Wellness"),
        ("Weight Loss", "Weight Loss"),
        ("Yoga", "Yoga"),
        ("Meditation", "Meditation"),
        ("Diet Plans", "Diet Plans"),
        ("Healthy Recipes", "Healthy Recipes"),
        ("Self-care", "Self-care"),
        ("Holistic Health", "Holistic Health"),
        ("Health Conditions", "Health Conditions"),
    ),
    "Fitness": (
        ("Cardio", "Cardio"),
        ("Strength Training", "Strength Training"),
        ("HIIT", "HIIT"),
        ("Pilates", "Pilates"),
        ("CrossFit", "CrossFit"),
        ("Running", "Running"),
        ("Cycling", "Cycling"),
        ("Yoga", "Yoga"),
        ("Dance Fitness", "Dance Fitness"),
        ("Bodyweight Exercises", "Bodyweight Exercises"),
        ("Sports Training", "Sports Training"),
        ("Fitness Gear", "Fitness Gear"),
    ),
    "Parenting": (
        ("Pregnancy", "Pregnancy"),
        ("Newborns", "Newborns"),
        ("Toddlers", "Toddlers"),
        ("Preschoolers", "Preschoolers"),
        ("Elementary Schoolers", "Elementary Schoolers"),
        ("Teenagers", "Teenagers"),
        ("Parenting Tips", "Parenting Tips"),
        ("Parenting Styles", "Parenting Styles"),
        ("Child Development", "Child Development"),
        ("Parenting Challenges", "Parenting Challenges"),
        ("Parenting Humor", "Parenting Humor"),
        ("Single Parenting", "Single Parenting"),
    ),
    "Technology": (
        ("Gadgets", "Gadgets"),
        ("Internet", "Internet"),
        ("Artificial Intelligence", "Artificial Intelligence"),
        ("Machine Learning", "Machine Learning"),
        ("Robotics", "Robotics"),
        ("Cybersecurity", "Cybersecurity"),
        ("Augmented Reality", "Augmented Reality"),
        ("Virtual Reality", "Virtual Reality"),
        ("Smart Home", "Smart Home"),
        ("Wearable Technology", "Wearable Technology"),
        ("IoT (Internet of Things)", "IoT (Internet of Things)"),
        ("Tech Reviews", "Tech Reviews"),
    ),
    "Gaming": (
        ("Video Games", "Video Games"),
        ("PC Gaming", "PC Gaming"),
        ("Console Gaming", "Console Gaming"),
        ("Mobile Gaming", "Mobile Gaming"),
        ("Gaming News", "Gaming News"),
        ("Game Reviews", "Game Reviews"),
        ("Gaming Guides", "Gaming Guides"),
        ("Esports", "Esports"),
        ("Gaming Events", "Gaming Events"),
        ("Gaming Industry", "Gaming Industry"),
        ("Retro Gaming", "Retro Gaming"),
        ("Gaming Culture", "Gaming Culture"),
    ),
    "Pets": (
        ("Dogs", "Dogs"),
        ("Cats", "Cats"),
        ("Birds", "Birds"),
        ("Fish", "Fish"),
        ("Small Pets", "Small Pets"),
        ("Reptiles", "Reptiles"),
        ("Exotic Pets", "Exotic Pets"),
        ("Pet Health", "Pet Health"),
        ("Pet Training", "Pet Training"),
        ("Pet Adoption", "Pet Adoption"),
        ("Pet Care Tips", "Pet Care Tips"),
        ("Pet Behavior", "Pet Behavior"),
        ("Pet Product Reviews", "Pet Product Reviews"),
    ),
    "Automotive": (
        ("Car Reviews", "Car Reviews"),
        ("Car Maintenance", "Car Maintenance"),
        ("Car Modifications", "Car Modifications"),
        ("Car Racing", "Car Racing"),
        ("Classic Cars", "Classic Cars"),
        ("Electric Vehicles", "Electric Vehicles"),
        ("Motorcycles", "Motorcycles"),
        ("Trucks", "Trucks"),
        ("SUVs", "SUVs"),
        ("Off-Roading", "Off-Roading"),
        ("Car Buying Tips", "Car Buying Tips"),
        ("Automotive Industry", "Automotive Industry"),
    ),
    "Movies": (
        ("Movie Reviews", "Movie Reviews"),
        ("Upcoming Movies", "Upcoming Movies"),
        ("Film Festivals", "Film Festivals"),
        ("Actors", "Actors"),
        ("Directors", "Directors"),
        ("Movie Genres", "Movie Genres"),
        ("Classic Movies", "Classic Movies"),
        ("Oscar-winning Movies", "Oscar-winning Movies"),
        ("Movie Soundtracks", "Movie Soundtracks"),
        ("Movie Analysis", "Movie Analysis"),
        ("Cinematography", "Cinematography"),
        ("Film Industry", "Film Industry"),
    ),
    "Books": (
        ("Book Reviews", "Book Reviews"),
        ("Bestseller Lists", "Bestseller Lists"),
        ("Literary Fiction", "Literary Fiction"),
        ("Mystery & Thrillers", "Mystery & Thrillers"),
        ("Science Fiction", "Science Fiction"),
        ("Fantasy", "Fantasy"),
        ("Romance", "Romance"),
        ("Biographies & Memoirs", "Biographies & Memoirs"),
        ("Historical Fiction", "Historical Fiction"),
        ("Young Adult (YA)", "Young Adult (YA)"),
        ("Poetry", "Poetry"),
        ("Non-fiction", "Non-fiction"),
        ("Book Clubs", "Book Clubs"),
    ),
    "Home": (
        ("Home Decor", "Home Decor"),
        ("Interior Design", "Interior Design"),
        ("DIY Home Projects", "DIY Home Projects"),
        ("Home Improvement", "Home Improvement"),
        ("Gardening", "Gardening"),
        ("Home Organization", "Home Organization"),
        ("Cleaning Tips", "Cleaning Tips"),
        ("Home Renovation", "Home Renovation"),
        ("Furniture", "Furniture"),
        ("Home Appliances", "Home Appliances"),
        ("Home Safety", "Home Safety"),
        ("Home Automation", "Home Automation"),
    ),
    "Gardening": (
        ("Vegetable Gardening", "Vegetable Gardening"),
        ("Flower Gardening", "Flower Gardening"),
        ("Indoor Plants", "Indoor Plants"),
        ("Herb Gardening", "Herb Gardening"),
        ("Garden Design", "Garden Design"),
        ("Landscaping", "Landscaping"),
        ("Garden Pests", "Garden Pests"),
        ("Composting", "Composting"),
        ("Container Gardening", "Container Gardening"),
        ("Gardening Tools", "Gardening Tools"),
        ("Garden Maintenance", "Garden Maintenance"),
        ("Garden DIY Projects", "Garden DIY Projects"),
    ),
    "Finance": (
        ("Personal Finance", "Personal Finance"),
        ("Investing", "Investing"),
        ("Saving & Budgeting", "Saving & Budgeting"),
        ("Credit & Debt", "Credit & Debt"),
        ("Retirement Planning", "Retirement Planning"),
        ("Real Estate", "Real Estate"),
        ("Stock Market", "Stock Market"),
        ("Financial Tips", "Financial Tips"),
        ("Financial Planning", "Financial Planning"),
        ("Cryptocurrency", "Cryptocurrency"),
        ("Tax Planning", "Tax Planning"),
        ("Financial Literacy", "Financial Literacy"),
    ),
    "Photography": (
        ("Photography Tips", "Photography Tips"),
        ("Camera Gear", "Camera Gear"),
        ("Portrait Photography", "Portrait Photography"),
        ("Landscape Photography", "Landscape Photography"),
        ("Street Photography", "Street Photography"),
        ("Wildlife Photography", "Wildlife Photography"),
        ("Macro Photography", "Macro Photography"),
        ("Travel Photography", "Travel Photography"),
        ("Black & White Photography", "Black & White Photography"),
        ("Photography Techniques", "Photography Techniques"),
        ("Photography Editing", "Photography Editing"),
        ("Photography Inspiration", "Photography Inspiration"),
    ),
    "DIY": (
        ("DIY Home Projects", "DIY Home Projects"),
        ("Crafts", "Crafts"),
        ("Woodworking", "Woodworking"),
        ("Sewing", "Sewing"),
        ("Painting", "Painting"),
        ("Upcycling", "Upcycling"),
        ("DIY Fashion", "DIY Fashion"),
        ("DIY Beauty", "DIY Beauty"),
        ("DIY Gifts", "DIY Gifts"),
        ("DIY Electronics", "DIY Electronics"),
        ("DIY Repairs", "DIY Repairs"),
        ("DIY Tutorials", "DIY Tutorials"),
    ),
    "Spirituality": (
        ("Meditation", "Meditation"),
        ("Mindfulness", "Mindfulness"),
        ("Yoga", "Yoga"),
        ("Spiritual Growth", "Spiritual Growth"),
        ("Religion", "Religion"),
        ("Astrology", "Astrology"),
        ("Tarot", "Tarot"),
        ("Spiritual Healing", "Spiritual Healing"),
        ("Alternative Medicine", "Alternative Medicine"),
        ("Energy Healing", "Energy Healing"),
        ("Spiritual Practices", "Spiritual Practices"),
        ("Spiritual Wisdom", "Spiritual Wisdom"),
    ),
}
